export  const POST_CONTACTDATA = 'POST_CONTACTDATA';
export  const GET_CONTACTDATA = 'GET_CONTACTDATA';
export  const SET_CONTACTDATA = 'SET_CONTACTDATA';
export  const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED';