export  const POST_CONTACTDATA = 'POST_CONTACTDATA';

export  const SET_CONTACTDATA = 'SET_CONTACTDATA';

export  const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED';
export  const SUCCESS_LOAD_DATA = 'SUCCESS_LOAD_DATA';
export  const FAILED_LOAD_DATA = 'FAILED_LOAD_DATA';

export  const GET_CONTACTDATA_START = 'GET_CONTACTDATA_START';
export  const GET_CONTACTDATA_SUCCESS = 'GET_CONTACTDATA_SUCCESS';
export  const GET_CONTACTDATA_FAILED = 'GET_CONTACTDATA_FAILED';

////firebase
export const FIREBASE_GET_DATA_START = 'FIREBASE_GET_DATA_START';
export const FIREBASE_GET_DATA_SUCCESS = 'FIREBASE_GET_DATA_SUCCESS';
export const FIREBASE_GET_DATA_FAIL = 'FIREBASE_GET_DATA_FAIL';

export const FIREBASE_DELETE_DATA = 'FIREBASE_DELETE_DATA';


