export  const POST_CONTACTDATA = 'POST_CONTACTDATA';
export  const GET_CONTACTDATA = 'GET_CONTACTDATA';
export  const SET_CONTACTDATA = 'SET_CONTACTDATA';
export  const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED';


export  const SUCCESS_LOAD_DATA = 'SUCCESS_LOAD_DATA';
export  const FAILED_LOAD_DATA = 'FAILED_LOAD_DATA';